server:
  port: ${APP_PORT:8083}

spring:
  application:
    name: file-status-processor
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      authentication-database: ${MONGODB_AUTH:admin}
      username: ${MONGODB_USERNAME:user}
      password: ${MONGODB_PASSWORD:pass}
      database: ${MONGODB_DATABASE:filestatus}
      auto-index-creation: true
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost:9092}
    consumer:
      groupId: file-status-processor-id