server:
  port: ${APP_PORT:8080}

spring:
  application:
    name: file-loader
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost:9092}
    consumer:
      groupId: file-uploader-id
file-status-processor-url: ${FILE_STATUS_PROCESSOR_URL}
